### ISSUE TITLE
Consider adding a factory method

### ISSUE THREAD

**Issue by zeke** [sindresorhus/conf#10]
I know it's "idiomatic", but I've never been a fan of this style for requiring a class that will only be instantiated once:

```js
const Conf = require('conf');
const config = new Conf();
```

What about adding a factory method like this:

```js
const conf = require('conf').new();
```

or even:

```js
const conf = require('conf')();
```

This could be supplemental to the existing instantiation behavior.

**Comment by mceachen** [comment]
somewhat related: this isn't a great first impression:

```bash
$ npm install conf
$ node # NEW TOY OMG SO EXCITED
> const Conf = require('conf')
TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:697:5)
    at Object.<anonymous> (..\node_modules\conf\index.js:13:24)
# sad trombone 😢
```
because node's REPL has no module.parent:
```
$ node
> module.parent
undefined
```

```
$ node -v
v6.6.0
$ uname -a
MINGW64_NT-10.0 xps15 2.5.0(0.295/5/3) 2016-03-31 18:47 x86_64 Msys
```

**Comment by zeke** [comment]
`uname -a`

😎

**Comment by sindresorhus** [comment]
@zeke I was back-and-forth on that before publishing, but I thought a constructor made sense since most are gonna want to set some default values in the `defaults` options, so they need to use the constructor.

> I know it's "idiomatic", but I've never been a fan of this style for requiring a class that will only be instantiated once:

It's not certain it will only be instantiated once. A module may want multiple instances.

-

```js
const conf = require('conf').new();
const conf = require('conf')();
```

These styles won't work for ES2015 imports. I don't think it makes sense to optimize for something that will go away.

-

Happy to continue discussing this though.

**Comment by sindresorhus** [comment]
@mceachen Your issue is unrelated to this, but thanks for bringing it up :) I never thought of the use-case of using this module in the REPL. I'll make sure to improve that experience.

**Comment by zeke** [comment]
> These styles won't work for ES2015 imports

Good point. Not on that 🚋  yet.
