### ISSUE TITLE
Support running it in a REPL

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/conf#11]
See: https://github.com/sindresorhus/conf/issues/10#issuecomment-249320242

**Comment by florianb** [comment]
Other than stated in #10, this fails because conf's `module.parent.filename` is `null`. As a first try i added support for the local `package.json` in the pending pr. 

Even though pkg-up does as it says (it searches upwards) it would be nice if there would be an option to also recognize a package.json in the cwd, too.

**Comment by florianb** [comment]
🤔 huh, i haven't really tried if pk-up doesn't do that already.

**Comment by florianb** [comment]
✍️  Okay pkg-up also recognizes the local package.json, except in the test-environment. I currently have no idea why `pkgUp.sync(process.cwd())` returns `null` when being invoked from within a test.

**Comment by florianb** [comment]
Stupidness solved.
