### ISSUE TITLE
Write file atomically?

### ISSUE THREAD

**Issue by mvayngrib** [sindresorhus/conf#12]
instead of writeFileSync

**Comment by sindresorhus** [comment]
Why?

**Comment by mvayngrib** [comment]
sometimes when node crashes, files getting written end up blank. write-file-atomic prevents it. I noticed configstore uses it, and i was using it in my project instead of writeFileSync, so i thought i'd suggest it

**Comment by sindresorhus** [comment]
I only have bad experience with the `write-file-atomic` module after having used it in Configstore. Bad code and maintenance. I'm happy to consider a different module if it's good.

**Comment by mvayngrib** [comment]
ok, since i don't know of another one, i'll close this for now

**Comment by danielweck** [comment]
For visitors in the future, `conf` uses `atomically`, not the default `fs` API:

https://github.com/sindresorhus/conf/blob/a96e9d78ac7e675a24ed702f1c21dd46a0b3ae0e/source/index.ts#L457

https://github.com/fabiospampinato/atomically

**Comment by danielweck** [comment]
CC @jurepetrovic

**Comment by jurepetrovic** [comment]
Hello Gentlemen, 

to solve this issue on windows we were forced to fork the atomically and conf projects. 
In case of error, we fallback to the fs module of the node. We did not go deeper, as 
already this solution required forking of electron store and conf. I believe some of the 
changes were pulled into main projects. 

You can look here: 
https://github.com/jurepetrovic/conf-atomically/blob/master/source/index.ts

and here:
https://github.com/jurepetrovic/electron-store-atomically
This fork is only that is used different conf.

This solution works for us perfectly since then.
