### ISSUE TITLE
Can't store Node.js Timeout object

### ISSUE THREAD

**Issue by selrond** [sindresorhus/conf#28]
An attempt to store Timeout (a [return value](https://nodejs.org/api/timers.html#timers_setinterval_callback_delay_args) from `setInterval` and `setTimeout` functions in Node) inside conf results in 
```shell
TypeError: Converting circular structure to JSON
``` 

Example code:
```javascript
const getTimerObject = () => {
	return config.get("timerObject") || null;
};

const setTimerObject = newTimerObject => {
	config.store = newTimerObject;
	return getTimerObject();
};

const currentInterval = setTimeout(() => console.log("tick"), 3000);

const savedCurrentInterval = setTimerObject(currentInterval); // fails here
```

Any way I can work around this? I need to store it to be able to cancel it on demand, based on user input. (Purpose: Alfy based Alfred Workflow)

**Comment by sindresorhus** [comment]
The value you set must be JSON serializable. You could store a timestamp instead and use that.

**Comment by selrond** [comment]
@sindresorhus could you elaborate on that? How can I `clearTimeout()` with timestamp?

**Comment by sholladay** [comment]
@selrond This is what I would do. Below is a `setEnd()` function that behaves like `setTimeout()`, except it persists when the timer should trigger. If an end timer already exists but has not been triggered, then the handler will be called at the previously calculated end time, ignoring the given delay. The system is reset when the timer triggers.

In the event that the timer _should have_ been triggered in the past but didn't (e.g. the app was not running at the time), then the handler will be called with the minimum timer delay (basically zero). This makes it appropriate for use in an initialization routine. The handler will be called as close as possible to the originally scheduled time, whether that be in the past or future.

```
const clearEnd = (timer) => {
    clearTimeout(timer);
    conf.delete('end');
};

const setEnd = (fn, delay, ...args) => {
    const end = conf.has('end') ? conf.get('end') : Date.now() + delay;
    conf.set('end', end);
    return setTimeout(() => {
        clearEnd();
        fn(...args);
    }, end - Date.now());
};

const endTimer = setEnd(() => {
    console.log('This is the end');
}, 3000);

// clearEnd(endTimer);
```

**Comment by selrond** [comment]
@sholladay Thank you! 

Now how would you do it for `setInterval()`? I choose `setTimeout()` in the example, because is easier to work with (don't have to kill the Node process each time I can't stop it in code and returns the same `Timeout` object as `setInterval()`).

What I really want to do is:

1. Run timer
2. Save a reference to it to the `conf` instance
3. Do some stuff
4. Be able to stop the timer by getting it from `conf`

How would you approach it?

**Comment by sholladay** [comment]
The same principles apply. Regardless of your exact timer setup and usage, the key is to turn the delay into absolute time (i.e. using `Date.now()`) and then keep `conf` up to date on when the next "tick" should be. Your program can then pick up where it left off at any point in the future by making a new timer. There's no reason it needs to persist the actual original timer object. It just needs to reconstruct it, if necessary.

The only thing that is a bit weird about the interval case is the lack of a single timer object, at least the way I wrote it below using [a recursive timeout](https://javascript.info/settimeout-setinterval#recursive-settimeout), to ensure it begins ticking at the appropriate moment. So stopping the cron is a bit different. There is a more convoluted way to do this if you do actually want the semantics of `setInterval()` or need to return an interval object, but I'll assume for the moment that isn't necessary.

Also note that using intervals of < 200ms or so is probably a bad idea here. `conf` is reading and writing to disk synchronously, which will take time. Depending on what `fn()` is doing, short intervals may end up running less frequently than you would expect. You can switch to using `setInterval` instead of a recursive timeout to fix this, but the tradeoff is that it may skip a beat if the CPU is busy at the time. Which way is "correct" depends solely on your needs.

```js
const cron = (fn, delay, ...args) => {
    const next = conf.has('next') ? conf.get('next') : Date.now() + delay;
    conf.set('next', next);
    let timeout = setTimeout(function tick() {
        conf.set('next', Date.now() + delay);
        fn(...args);
        timeout = setTimeout(tick, delay);
    }, next - Date.now());

    return () => {
        clearTimeout(timeout);
        conf.delete('next');
    };
};

const stopCron = cron(() => {
    console.log('This is a heartbeat');
}, 3000);

// stopCron();
```

**Comment by selrond** [comment]
@sholladay Thank you!
What I didn't realize is that where I want to use it (Alfy workflow), it basically runs `node index.js` every time conditions are met. 

So I _guess_ the reason I wasn't able to get it working was, that Node created new process every time it was invoked to run `node index.js` (Am I right though? Not entirely sure how Node works in such manner). 

So I guess there is not an approachable way to get it working in Node...

**Comment by sholladay** [comment]
The code I provided above is designed to work across restarts of Node (or even restarting your entire computer). The only requirement is that Node be running at the time when the `tick` is supposed to happen. In other words, let's say you wanted to report something about your app to [Google Analytics](https://analytics.google.com/) every 30 seconds. My timer code above would be able to do that and it would _remember to keep doing that_ even if the process was restarted (assuming you have an initialization function that runs my code). The only thing it _wouldn't_ do is magically keep going after the process exits. However, the timer _is_ supposed to keep Node open, so the process would have to be closed by external means in order to even need to use `conf` at all.

My best guess at this point is that either Alfy forces Node to close prematurely (try adding handlers for [SIGTERM and SIGINT](https://nodejs.org/api/process.html#process_signal_events) to prevent this), or that your initialization code in `index.js` is wrong (e.g. it is not calling `cron()`).

**Comment by selrond** [comment]
@sholladay I really do appreciate your time and help, but I can't seem to get it working. I've already spent too much time on this, tried tens of different approaches, and now I'am almost totally burnt out on it... 

If there's any chance you know how Alfred works, and happen to be bored, here's my repo: https://github.com/selrond/alfred-standup

Thank you again
