### ISSUE TITLE
package.json autodetection fails if not used as a direct dependency

### ISSUE THREAD

**Issue by jwheare** [sindresorhus/conf#7]
As noted in: https://github.com/sindresorhus/electron-config/issues/1#issuecomment-234117691

Perhaps this can just be mentioned in the README as a caveat, but if no `projectName` or `cwd` is provided, conf tries to detect the package.json of the parent package.

However, this uses the module.parent mechanism, which returns the nearest direct dependent, rather than the top level package.

https://github.com/sindresorhus/conf/blob/c5a736b061f5a844e2e4dd99bfff8144dee5f47a/index.js#L13

This can cause issues if a module is using conf via an intermediary.

**Comment by sindresorhus** [comment]
The problem is that we can't really know which module in the tree is the correct one. It might be the direct parent, it might be top level, or somewhere in between. I think auto-detecting the direct one and falling back to an option is a good compromise, but happy to consider other solutions. And yes, should be documented better regardless.
